export const skills = [
  // Skills
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Web Design",
  "Mobile App Development",
  "UI/UX Design",
  "Database Management",
  "Cloud Computing",
  "Machine Learning",
  "Data Analysis",
  "Digital Marketing",
  "Content Writing",
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Music Production",
  "Illustration",
  "Animation",
  "Game Development",
  "Cybersecurity",
  // Interests
  "Traveling",
  "Reading",
  "Cooking",
  "Hiking",
  "Fitness",
  "Gaming",
  "Gardening",
  "Drawing",
  "Painting",
  "Writing",
  "Blogging",
  "Podcasting",
  "Public Speaking",
  "Volunteering",
  "Learning Languages",
  "Investing",
  "Coding",
  "DIY Projects",
  "Fashion",
  "Technology",
  "Robotics",
  "Astronomy",
  "History",
  "Philosophy",
  "Sociology",
  "Psychology",
  "Economics",
  "Politics",
  "Environmentalism",
  "Photography",
  "Film Making",
  "Music",
  "Dancing",
  "Yoga",
  "Meditation",
  "Crafting",
  "Sewing",
  "Knitting",
  "Board Games",
  "Puzzles",
  "Martial Arts",
  "Swimming",
  "Cycling",
  "Running",
  "Tennis",
  "Football",
  "Basketball",
  "Baseball",
  "Soccer",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Scuba Diving",
  "Fishing",
  "Bird Watching",
  "Camping",
  "Collecting",
  "Traveling",
  "Exploring Nature",
  "Astronomy",
  "Astrology",
  "Magic Tricks",
  "Stand-up Comedy",
  "Storytelling",
  "Theater",
  "Opera",
  "Ballet",
  "Circus Arts",
  "Juggling",
  "Parkour",
  "Slacklining",
  "Origami",
  "Woodworking",
  "Metalworking",
  "Pottery",
  "Glass Blowing",
  "Leatherworking",
  "Calligraphy",
  "Scrapbooking",
  "Genealogy",
  "Cryptography",
  "Puzzle Solving",
  "Escape Rooms",
  "Kite Flying",
  "RC Cars",
  "RC Planes",
  "Drone Flying"
];

export const getRandomSkills = (numSkills: number) => {
  const shuffledSkills = skills.sort(() => Math.random() - 0.5);
  return shuffledSkills.slice(0, numSkills);
};
